apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-local-zim
  namespace: kiwix
  labels:
    app: kiwix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
