apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/headscale
  - ../../../base/headplane
  - namespace.yaml
  - configmap-headscale.yaml
  - configmap-headplane.yaml
  - ingress-headscale.yaml
  - ingress-headplane.yaml
  - middleware.yaml
  - sealed-headplane-cookie-secret.yaml

patches:
  # Use local-path storage on k3s
  - target:
      kind: PersistentVolumeClaim
      name: headscale-data
    patch: |
      - op: add
        path: /spec/storageClassName
        value: local-path
  - target:
      kind: PersistentVolumeClaim
      name: headplane-data
    patch: |
      - op: add
        path: /spec/storageClassName
        value: local-path
