apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headplane-config
  namespace: headscale
spec:
  encryptedData:
    config.yaml: AgCXoSMhBigQZKjYsTCHvhL+Q709JnWYdaiq6H+uSqT/1MnBYE9Uq+fY1e7CrNwzt22EpS+VNbsl6/dWtBQZq1uX7NUGzn46bi4ruWr9UVUanD2m93qaZ2fuoiVav0FIV8FjHQbKaucqfcBYzzhbUA+FomJf0H+YzgdXByn1C0p5AdDr/LC9wefas/hW55JM+qR19sT8qF/z7Y3Ha67jOCuzgapV/hRecKVNf4ZlynDbgQjdLQJGSVsT4IcfLDH8nYR4N3r9qMgMZ33elfSFwa+RThuPW5t1zAopWI2mp98uL39gnmpNCLZixwd+/O3YegMcJJ+yARxU7vBxY0FXniXXdlU4wO/yk8LWtgAkjiX2yWbsx0HadnadEqp/Eldc82mKqTXSdx+D8fgkzqf/dnnuD5k1sNpwlGq2AFzI3yhCR0mJbJ9DgvHbMLiPoBRO8PchK+akwQQ6+U2k9ME3JZU4xoA/bxFWwTOaJxVlsIDn9c63A6sKf8xZbUxOimGc7g/rYhImf3KfSZsv3Ydyw3scMBD8D34gIkHfM+FJp/wM3RzEY19YsMWRzAeFhcTF9bUhrJPKf3rTdaZiJt2LhLD4PYarFnMMKv2Dod374HsvmyCqwKYcFrNYRysSAZo0CoA7mdg8jCuDHAOaOlcsuENXeiSn7K4kAOxfC+uLvnDyf1tOq7ZSPxurxvnTPYaLY0oCdr3DPK2sZesdxwtqco201bIHUnQ0VeEQgCvZQFpuuhbXAa0gNK2B+ZHzWwuTqDq/huiZkVoWU4lF4xTbLHJyekdgp+6IiCqxeAmgopYV/VSmdhFLvnNxDsSugB32OcMSO6swrzL9mkOV3R+Uf22wBfkcnqElx+Va67SplZ1ppjCV+ev2ZMKoR/+leno8SW5fTQLHeTACP2el0WYBwAH9e1krbIKuob+uTUQoay7dQ0PTFaQC+/GGpChteSyzuWhT8co5snBG3Pqr6i5QKPNvwRPdUX5QaLJfLArIR60=
  template:
    metadata:
      name: headplane-config
      namespace: headscale
