apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headplane-config
  namespace: headscale
spec:
  encryptedData:
    config.yaml: AgDdh5kxM/xzHwnLTptmh74MKVtFsDBomshPhV5R+G2nSsUAJoSL0V+Y+U3SC0+n4mJwGcz3ovBqIQl5WWpX6dfPXEj9bEkNxRK/rhdJGlYPIVCQcuhgsAzMPFll1m/ImDZWan6ZNC8MYLdgCT+UUwUwrQfb3oxYcAZDsAROwerXbShDBtz5L99wo6d1GTLz6ZATanh7UaPoG5NAXXEBXjl+eJmFlvXqznv/p2C3+Jjpof5/F62wYn/CBoQQtz54OnVQ1SCEvkprc6I5ribmBeMjjPEYZu6RYcz2xJsiTPxitD8d2kHSprFTqmF6dj4AEGJVNmc52y1CuGcTWJtXDiG4RMHgm9juuF7p/zWJIdypIlIBms/qzGgbPfyFUnOFCNFLfMsZoi9adNjeQcm1RflZuG85ki53YYQ3WIQ31Z0C/pazvC4nKPRtShvGeSKUmP1w0cszBlmLfaXt6X1ywvd8xHnKCG8oK2Uea0ZX2O+dBSWKZ7UnIkyD5NLZQAAPxLaCKcrWNUsmhOF6ZIn31Tq6DFx9aSUwjXe1G/JVQ3zZvIcod+B4H5OZaevSSysR6HMR6GYTRqf+r5p2px6apW8+DwbFZDM0cakIpCUckHIq5kt4adxs0USg3xj5T3pZooYvG4k3iGBui0Z8bjxd9qgF4AvFISrEtHPyJbtGOQEHdG7JJYVVCaxD+ddoMJaLuETWHtXbqHz521epbzHNMoaFBcmWiFgCrY0uk7trwhiSrkqjEmBnYvIZZo/x0eJ5TXOzywWxySis5fYQb1TcpJawdLriKgEODU1t3sZU9SHXlqtEdTJNmXYHUyKr3YvPbluJFGzNcPb9PR0f17EeiTMz3Tsm+2WkOjc6nlvj7YREroPBPBwsJ5rqoqiiif7TFIWWfPfAoRn6jfTI5p+sWb0DFw4qVFDK4oxqO66Z54WmwQ28QKz33d7nWuP1WmGqZjrOMFl02PjTGiDtD085Bpev1pJkvFz53JQg8jgR4yyM+J+Df5AN8aKYdYXXgxcr5hzkWIGkkG/lnQipMt+KNg==
  template:
    metadata:
      name: headplane-config
      namespace: headscale
