apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headplane-cookie-secret
  namespace: headscale
spec:
  encryptedData:
    cookie-secret: AgCXCJd+G9fTKSv6rD/qnc5BlW0wZdvmTDXexQvJDfkVVNJKmfhLNQE+CPCtzXeODrYS2bm5QmpFvTebIP8UpsMWO7YI+7/XakvsVg9IFwFmTZmJr3VRQbi6/6x7UaOm329TmD4dD11mkjPqlNPhPGrPiRk1iSIKgHasOfb1rbPPhwdc7lib43g7E5hdAHaRvyyjakrpI/TDwAi9m2RfXuwcMVlpQ1VjJxiORjxXiwH16NtdreWFp+ETwhn4/e1eDNzGNjs9Rop5ARjq1hO+7Ai6CP06Jf97VxcdK3x+S1XZL7AHOG+DBISvYnuHqY+G2JoiWZRN/KM1+X3gr8KK/NNHizl9jGlNWwvEh8X6s/siEN++8lPVsWSeAt1432KNjc45kkzpz7Vka22b6QXKVETEH818HXH4yuOhJhymDxj+QRPqDxb6bpGTIPXrmXj4Z/JHG57gTcdQLQTzSHl8NhHh1MAZGbdTd14sh+VpvDA/MTZKlzcNGeJ1PcqomvhzfP1qbiftl8hFuTtmYHSrO109/nfxTKFYUXef1Px7eX7pUS3vgPVrK39Jtzbsc3M9l9Qea4MhyRVj4+xgXKB4Tz3a20+ePeEXSz+jTNyGiL94MhKT/CRVZ/h79wfkwbLr4Xpk/e/gOdr7LHdfFQjSFQMrrFdF/OM7dmru7KZFXmOeaNeom3IEFW+R5x5CEUaYmoEzNeCBEhivMJuGdimaDW+kD5uMU4BkdunxWxA2jxsUXFPlVTiWYhHo7I9q5EfNoATMnNlsXYkUb1XJ4ulgDSPH
  template:
    metadata:
      name: headplane-cookie-secret
      namespace: headscale
