apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headplane-data
  namespace: headscale
  labels:
    app: headplane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
