apiVersion: v1
kind: Service
metadata:
  name: infisical
  namespace: infisical
  labels:
    app: infisical
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: infisical
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infisical
  namespace: infisical
  labels:
    app: infisical
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: infisical
  template:
    metadata:
      labels:
        app: infisical
    spec:
      containers:
        - name: infisical
          image: infisical/infisical:v0.161.11
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: infisical-secrets
          env:
            - name: DB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: infisical-db-uri
                  key: uri
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: infisical-redis-uri
                  key: uri
          startupProbe:
            httpGet:
              path: /api/status
              port: http
            periodSeconds: 10
            failureThreshold: 90
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
            periodSeconds: 10
          resources:
            requests:
              cpu: 350m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
