apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: yopass-netpol
  namespace: yopass
  labels:
    app: yopass
spec:
  podSelector:
    matchLabels:
      app: yopass
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from Traefik ingress controller
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 1337
  egress:
    # DNS
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
