apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap-nginx.yaml
  - deployment.yaml
  - service.yaml

# TLS cert created separately via: kubectl create secret tls reverse-proxy-tls ...
