apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://codeberg.org/piotrkrzysztof/fleet.git
    path: clusters/hetzner/databases
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
