apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ntfy
  - namespace.yaml
  - configmap.yaml
  - ingress.yaml

patches:
  # k3s lacks network storage; use node-local provisioner
  - target:
      kind: PersistentVolumeClaim
      name: ntfy-cache
    patch: |
      - op: add
        path: /spec/storageClassName
        value: local-path
