---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: databases
spec:
  encryptedData:
    superuser-password: AgDBU7mpsDEHy6lIdTJzI+iyiQ6DEsIvO2eo3xG6i6HgbloBAYCyVFHeVtrTWS3sXrs9zxcY8mq2ZDsX2TxngN6J1h1nXGVeNeP5SG3h1bIwmUZSMJgKE0B9WZef6bnZMzjWDmWlZJTpLjS14jMm52efmu9mHAbGPSb/C7rDg6Q9EerfEP2/aCKhaxATv3ahqf0K0j6EdOFw/HPSxhawmP/KtyGuhOLX5bsFZSB0MhTvF+L7n0hfpKpde6FMJpnsrVGsqai7TgQVyYJIoDVRe5sjh2Kjwlb7Z/GwUovwpm6fLokX5mt76Vy70/MNQ4Cbp8ciHJ+ywmisw/a174/s+jNCxrdqM3AmpNil2wOG4n5XUmkqvmbofbJ93jGey6tdBgLtxgp/0A/RO3Oop2ovPZ/7QPnkjZGk6FnrBXVgWGwagx8seZgyIv7/GQD3tZ3TVxRzvgrI2krsd+f7Cg3KIWtGpB/cJ/yOgHZsXmK8Vsk2nKEtAWIiiU4TzGLf3nbq4/ttGnMfkzZTkzdMY22vhUcgTI+cbCY/o0DdujmMKmpXBtyjCJdQJDvMYX5FoXa35rd1bxZCJ3WfTZQgR3XNcH7YCbokPt7q4E/gfR1Ok3uO0rfSEZUBEyWdNKc72o8sOZEvF0Y99JLI3v05/1g/7XlT3RkKIVBV7EIY5aafUb51SKvIIBrsS8s4MWTKSTf6l+a3/Ntnuy3r4pBSst4meCxC3BzAPZwahby1L1c1BDb9hlBzIMIldCK+VB+kU0yk/0cIOMWD+Oe4THRZG3NG+/U+
  template:
    metadata:
      name: postgres-credentials
      namespace: databases
    type: Opaque
