apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/woodpecker-server
  - ../../../base/woodpecker-agent
  - namespace.yaml
  - configmap.yaml
  - ingress.yaml
  - sealed-woodpecker-agent-secret.yaml
  - sealed-woodpecker-db-datasource.yaml
  - sealed-woodpecker-oauth.yaml

patches:
  # Bump agent replicas to 2
  - target:
      kind: Deployment
      name: woodpecker-agent
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2

  # Bump server resources
  - target:
      kind: Deployment
      name: woodpecker-server
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

  # Bump agent resources
  - target:
      kind: Deployment
      name: woodpecker-agent
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi

  # k3s lacks network storage; use node-local provisioner
  - target:
      kind: PersistentVolumeClaim
      name: woodpecker-data
    patch: |
      - op: add
        path: /spec/storageClassName
        value: local-path
