apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/woodpecker-server
  - ../../../base/woodpecker-agent
  - namespace.yaml
  - configmap.yaml
  - ingress.yaml
  - sealed-woodpecker-agent-secret.yaml
  - sealed-woodpecker-db-datasource.yaml
  - sealed-woodpecker-oauth.yaml

patches:
  # Bump agent replicas to 2
  - target:
      kind: Deployment
      name: woodpecker-agent
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2

  # Use local-path storage on k3s
  - target:
      kind: PersistentVolumeClaim
      name: woodpecker-data
    patch: |
      - op: add
        path: /spec/storageClassName
        value: local-path
