---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-oauth
  namespace: woodpecker
spec:
  encryptedData:
    gitea-client: AgCKvA7KIB7DV84mkiUlJBkFPk9YcA0MnQ9pDgAVjK42BamfGf7WWYjsDxmmDQ9x9JCuz8IJH0bX2Z1TZAtJr/jNSOuYTQ+OuFPpp0xcrjOKUKwGqt1jMV//bH4AgD+Y+WZOvxoRFJ2ANaNHsANGtZ3pts/lB9+13dB7sNJsXsjHiDqNtAH5qx1gLrOsBUUft9e2Vax94tmRcnhpMjiFbuEe/x2gv0VUKvTLyvIH2wr38I02u8RX0jN4LYO6P795hMoXWt1QvCPvr0Rz/DZMbCZi5pTQNX+UJtkB3C9oE36kHEd/z5/29Cg2NXIbiKVFrAmT86eiuHKfYAJj2bFGF0Td9sXjSDkh9mxymFUg8+lJAhLlC5dcNMe5zzK6ME4mGaXcc2fzArYZGuoF2qEn1h1jLLjXFCh06muTPo/TrjxReMs3+ogC+jn1NbX2s0qdKTFLG+zFxeVwxqFG2pC0BS2tuLu5SvGCsoRzIN/Twch1z4phRVxAmmWiNunqfp0ltl+8pWUwvF16WdSWRBdsLR7a8HYQUHzzqPjMvWm8IeJtUg60H9pP/JkkKSgw27GxvkeWNXbEJU3puEtSuTtY4QRpEzWG8SRs9y2or75dcV08ZZno7/lRE0O5g5US4tSz4xinj34EveBVn+e4UR4BlS5qTr3ApK+pVf77VcWOfLydKeUkdYpvOPTiw16qycOXEkNMD+xJWoLrf8SLak6ahSqyM5MOpENcMgjDiUW958cNITVETOs=
    gitea-secret: AgDfTO2xB1yQHDOo+78mqX7gFLu1LpqAKonSvzdDwUgyLP/y5sK0aeJ9jqMzlNfOkYDaXT6k28YI3G+yKOMwqxufOmpnkPEF4ylQ8hkR2Hy3/TWrKXBtokGsPrTWgiIF7qg5Q20CYRucDZecTkzLJORRWpI3h4pw+80ejYkRITJU2n6GI52WgO4B43swBTiufdRxvKh08LAbcqj7+LIE9Hqyvy9GTl3X0T6RLskidQ3DaongeaN2aPP1QcHx3f0jEeu8WKogzOi3BIXLio6vlxMjvFgAxOMhQvfiOF8PAya44o57ciCtPYUqgDAOQgFmKrS/bVEwPcMIImtenGiMoPCcghS3AiSSBYu4O/8IZK6oCodyhARvUnFlUsOLqxM89j8+/2ZYtdJW/XYjvU64cZhlFxPZECicJ9qfIjLRM8aDGMw1eS7fWyOkVutE17UC3uBhAe8HRWLqHLatsPq4vDwsGzgoAT6L/RDWjimL63Tc/Y6BHdlXrfmAmCL3KspW+jajABm5uehPzWcveLuNYP46s4tgd2DEC+gmGTGi11hk5cXbJuzwQRT1q/ZGZIYrYosmKjmES8JSfZeDvCRQ40cTOaZ7ammUmieoUZKPdxK6x7QM+ZrZVshqSW5B87XAvynz6NX5lAUxL59ZKuCmuKbtKq56LEo0Kkv36OVilrUarioPOwLq5XMm/q3Ey4/wJzvjAeuWtuIuyeS9Bdq0WOvymjh6bmiS0qsqMGfqUlnxPejFhDJsmrLM68dmUQC7yuFefEEpbLi8CQ==
  template:
    metadata:
      name: woodpecker-oauth
      namespace: woodpecker
    type: Opaque
