---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-agent-secret
  namespace: woodpecker
spec:
  encryptedData:
    agent-secret: AgDNK20SU9nK7V4lxGIPWIqgu3v931dF17jV4nLJ7ql1Xw5vljXf9/cHIVs6uKuGZt2qt+4XtvXNYrLtMWxZnu6Mia4Kg9aq2AD4+QErPz7DiOXrBqgLzao/KM51dP7mqMA+2J1VWN3ZcU6yHraxoOcobPuZZLJ1o3JmhjtC2L27NMxBDK/uYQ4bevOz92zlb2ONKhlcSiYj49zWhneOP7j+q7Wbc5Kkk+gE7TJb1cy3V+LkPU7+mrobJhHjrLfpGW+OUn0DT+esqxucd87Oww2b+GE7L2D8GNtAwxgnx2Z+q52tsYdT4yAusGUW4kNEND2Kp9Q17vPDcO+VwuY3t/ldqxOOFalWxmSBpGzAt35eifEDn6+4wSq6spOxBc/3K1R4Vtjf+RKY73WSmFdb6AImzHOYKr0CZr/F4Lgk2Nn4VG5DKS6ewv93/1iMD22pNmVFKUvcIfj9Lg2h6XAOdEpCFx/ItqPTxDWXN+87ZvVkrt2G82pqGtwtl0Qu8oSuvyQR8Xs+0jfB/cWZVglJmvBlSIWWheGBaxj8gWzSvk0O68GPrbfOT/w749wuCEPh6sAmC7+3BeGyWBXJc5r0grIWovuTzkQze2nMx8N4sNeSs54LKWyUdgssayiDGfHa9HtBJBKcMY24GQqU1H0zHCJiWHfw2JyvE6J27KGGChUHF6CL6Tpx5dfnGmXiDXe3y1/g5TjOZ5OhRi/vUJHoVzXpRRVKbhoNVPiM2dP+CMJoenrgv5FagZxb4a5FPs3oSqe9BU6LL8mG5PleL+KLzML6
  template:
    metadata:
      name: woodpecker-agent-secret
      namespace: woodpecker
    type: Opaque
