apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: node-exporter
  labels:
    app: node-exporter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9100
      targetPort: 9100
      protocol: TCP
  selector:
    app: node-exporter
